### ISSUE TITLE
URGENT: Password checked into repo

### ISSUE THREAD

**Issue by slifty** [prior-art-archive/query-parser-docker#6]
The `config/properties.env` contains sensitive information.

We need to:

1. Change the password
2. Remove the config file (replace it with a properties.env.template file)

**Comment by slifty** [comment]
Pushed directly to master due to the sensitive nature -- we may want to actually squash this all the way back to the original commit to wipe the history, though that would mean a force push to master which I'm worried might cause pain and suffering

**Comment by shikham01** [comment]
Can we wipe out the history and remove cache as well. Force push to master to remove all the information including elastic instance details is worth doing it . Can you please help.

**Comment by shikham01** [comment]
We can actually git pull locally all the changes done to this repo and delete this repo completely and then create a new repo and check in all the changes there.

**Comment by slifty** [comment]
Absolutely -- will do first thing tomorrow morning.

**Comment by slifty** [comment]
Deleting this issue.
